/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicAgentsRouteImport } from './routes/_public/agents'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicFaqsRouteImport } from './routes/_public/faqs'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAgentsRouteImport } from './routes/_authenticated/admin.agents'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin.content'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminPropertiesRouteImport } from './routes/_authenticated/admin.properties'
import { Route as AuthenticatedAdminRentalsRouteImport } from './routes/_authenticated/admin.rentals'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin.staff'
import { Route as AuthenticatedAdminTenantsRouteImport } from './routes/_authenticated/admin.tenants'
import { Route as PublicBlogIndexRouteImport } from './routes/_public/blog.index'
import { Route as PublicBlogSlugRouteImport } from './routes/_public/blog.$slug'
import { Route as PublicPropertiesIndexRouteImport } from './routes/_public/properties.index'
import { Route as PublicPropertiesSlugRouteImport } from './routes/_public/properties.$slug'
import { Route as PublicPropertiesSlugUnitsUnitIdRouteImport } from './routes/_public/properties_.$slug.units.$unitId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAgentsRoute = PublicAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqsRoute = PublicFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAgentsRoute =
  AuthenticatedAdminAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPropertiesRoute =
  AuthenticatedAdminPropertiesRouteImport.update({
    id: '/properties',
    path: '/properties',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRentalsRoute =
  AuthenticatedAdminRentalsRouteImport.update({
    id: '/rentals',
    path: '/rentals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTenantsRoute =
  AuthenticatedAdminTenantsRouteImport.update({
    id: '/tenants',
    path: '/tenants',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogSlugRoute = PublicBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPropertiesIndexRoute = PublicPropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPropertiesSlugRoute = PublicPropertiesSlugRouteImport.update({
  id: '/properties/$slug',
  path: '/properties/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPropertiesSlugUnitsUnitIdRoute =
  PublicPropertiesSlugUnitsUnitIdRouteImport.update({
    id: '/properties_/$slug/units/$unitId',
    path: '/properties/$slug/units/$unitId',
    getParentRoute: () => PublicRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/agents': typeof PublicAgentsRoute
  '/contact': typeof PublicContactRoute
  '/faqs': typeof PublicFaqsRoute
  '/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/properties': typeof AuthenticatedAdminPropertiesRoute
  '/admin/rentals': typeof AuthenticatedAdminRentalsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/properties/$slug': typeof PublicPropertiesSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/blog/': typeof PublicBlogIndexRoute
  '/properties/': typeof PublicPropertiesIndexRoute
  '/properties/$slug/units/$unitId': typeof PublicPropertiesSlugUnitsUnitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRoute
  '/about': typeof PublicAboutRoute
  '/agents': typeof PublicAgentsRoute
  '/contact': typeof PublicContactRoute
  '/faqs': typeof PublicFaqsRoute
  '/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/properties': typeof AuthenticatedAdminPropertiesRoute
  '/admin/rentals': typeof AuthenticatedAdminRentalsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/properties/$slug': typeof PublicPropertiesSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/blog': typeof PublicBlogIndexRoute
  '/properties': typeof PublicPropertiesIndexRoute
  '/properties/$slug/units/$unitId': typeof PublicPropertiesSlugUnitsUnitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/agents': typeof PublicAgentsRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/faqs': typeof PublicFaqsRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/properties': typeof AuthenticatedAdminPropertiesRoute
  '/_authenticated/admin/rentals': typeof AuthenticatedAdminRentalsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/_public/blog/$slug': typeof PublicBlogSlugRoute
  '/_public/properties/$slug': typeof PublicPropertiesSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
  '/_public/properties/': typeof PublicPropertiesIndexRoute
  '/_public/properties_/$slug/units/$unitId': typeof PublicPropertiesSlugUnitsUnitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/about'
    | '/agents'
    | '/contact'
    | '/faqs'
    | '/admin/agents'
    | '/admin/blog'
    | '/admin/content'
    | '/admin/leads'
    | '/admin/properties'
    | '/admin/rentals'
    | '/admin/staff'
    | '/admin/tenants'
    | '/blog/$slug'
    | '/properties/$slug'
    | '/admin/'
    | '/blog/'
    | '/properties/'
    | '/properties/$slug/units/$unitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/about'
    | '/agents'
    | '/contact'
    | '/faqs'
    | '/admin/agents'
    | '/admin/blog'
    | '/admin/content'
    | '/admin/leads'
    | '/admin/properties'
    | '/admin/rentals'
    | '/admin/staff'
    | '/admin/tenants'
    | '/blog/$slug'
    | '/properties/$slug'
    | '/admin'
    | '/blog'
    | '/properties'
    | '/properties/$slug/units/$unitId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/auth'
    | '/_authenticated/admin'
    | '/_public/about'
    | '/_public/agents'
    | '/_public/contact'
    | '/_public/faqs'
    | '/_public/'
    | '/_authenticated/admin/agents'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/properties'
    | '/_authenticated/admin/rentals'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/tenants'
    | '/_public/blog/$slug'
    | '/_public/properties/$slug'
    | '/_authenticated/admin/'
    | '/_public/blog/'
    | '/_public/properties/'
    | '/_public/properties_/$slug/units/$unitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/agents': {
      id: '/_public/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof PublicAgentsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faqs': {
      id: '/_public/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof PublicFaqsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/agents': {
      id: '/_authenticated/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AuthenticatedAdminAgentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/properties': {
      id: '/_authenticated/admin/properties'
      path: '/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AuthenticatedAdminPropertiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rentals': {
      id: '/_authenticated/admin/rentals'
      path: '/rentals'
      fullPath: '/admin/rentals'
      preLoaderRoute: typeof AuthenticatedAdminRentalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tenants': {
      id: '/_authenticated/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AuthenticatedAdminTenantsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/$slug': {
      id: '/_public/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof PublicBlogSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/properties/': {
      id: '/_public/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PublicPropertiesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/properties/$slug': {
      id: '/_public/properties/$slug'
      path: '/properties/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PublicPropertiesSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/properties_/$slug/units/$unitId': {
      id: '/_public/properties_/$slug/units/$unitId'
      path: '/properties/$slug/units/$unitId'
      fullPath: '/properties/$slug/units/$unitId'
      preLoaderRoute: typeof PublicPropertiesSlugUnitsUnitIdRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAgentsRoute: typeof AuthenticatedAdminAgentsRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminPropertiesRoute: typeof AuthenticatedAdminPropertiesRoute
  AuthenticatedAdminRentalsRoute: typeof AuthenticatedAdminRentalsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminTenantsRoute: typeof AuthenticatedAdminTenantsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAgentsRoute: AuthenticatedAdminAgentsRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminPropertiesRoute: AuthenticatedAdminPropertiesRoute,
  AuthenticatedAdminRentalsRoute: AuthenticatedAdminRentalsRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminTenantsRoute: AuthenticatedAdminTenantsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicAgentsRoute: typeof PublicAgentsRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicFaqsRoute: typeof PublicFaqsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBlogSlugRoute: typeof PublicBlogSlugRoute
  PublicPropertiesSlugRoute: typeof PublicPropertiesSlugRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
  PublicPropertiesIndexRoute: typeof PublicPropertiesIndexRoute
  PublicPropertiesSlugUnitsUnitIdRoute: typeof PublicPropertiesSlugUnitsUnitIdRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicAgentsRoute: PublicAgentsRoute,
  PublicContactRoute: PublicContactRoute,
  PublicFaqsRoute: PublicFaqsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicBlogSlugRoute: PublicBlogSlugRoute,
  PublicPropertiesSlugRoute: PublicPropertiesSlugRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
  PublicPropertiesIndexRoute: PublicPropertiesIndexRoute,
  PublicPropertiesSlugUnitsUnitIdRoute: PublicPropertiesSlugUnitsUnitIdRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
